# Amostragem
-----------

### Carregamento da base de dados

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
# Abrindo a base de dados census que possui os dados do Censo dos EUA
dataset = pd.read_csv('./Bases de dados/census.csv')
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

### Amostra Aleatória Simples

In [3]:
df_amostra_aleatoria_simples = dataset.sample(n=100) # Função que retorna um DataFrame de amostras escolhidas aleatoriamente
df_amostra_aleatoria_simples.shape

(100, 15)

In [4]:
df_amostra_aleatoria_simples.head()

age          workclass  final-weight      education  education-num  \
14617   38            Private        172571      Bachelors             13   
5363    28   Self-emp-not-inc        160786        HS-grad              9   
13317   49            Private        255559   Some-college             10   
8366    62            Private        121319      Bachelors             13   
9198    47            Private        189680      Bachelors             13   

            marital-status        occupation relationship    race      sex  \
14617   Married-civ-spouse   Exec-managerial      Husband   White     Male   
5363         Never-married      Craft-repair    Own-child   White     Male   
13317   Married-civ-spouse      Adm-clerical         Wife   White   Female   
8366    Married-civ-spouse    Prof-specialty      Husband   White     Male   
9198    Married-civ-spouse             Sales      Husband   White     Male   

       capital-gain  capital-loos  hour-per-week  native-country  income  
14617             0          1848             54   United-States    >50K  
5363              0             0             40   United-States   <=50K  
13317             0             0             40   United-States    >50K  
8366           3103             0             40   United-States    >50K  
9198              0          1977             40   United-States    >50K

### Amostragem Sistematica
Escolha sistematica da amostra em sua população

In [5]:
dataset.shape

(32561, 15)

In [6]:
# Desejo 100 amostra, no exemplo
len(dataset) // 100

325

In [7]:
# Escolho a cada 325 elementos da população
indices = np.arange(68, len(dataset), step=325)
indices

array([   68,   393,   718,  1043,  1368,  1693,  2018,  2343,  2668,
        2993,  3318,  3643,  3968,  4293,  4618,  4943,  5268,  5593,
        5918,  6243,  6568,  6893,  7218,  7543,  7868,  8193,  8518,
        8843,  9168,  9493,  9818, 10143, 10468, 10793, 11118, 11443,
       11768, 12093, 12418, 12743, 13068, 13393, 13718, 14043, 14368,
       14693, 15018, 15343, 15668, 15993, 16318, 16643, 16968, 17293,
       17618, 17943, 18268, 18593, 18918, 19243, 19568, 19893, 20218,
       20543, 20868, 21193, 21518, 21843, 22168, 22493, 22818, 23143,
       23468, 23793, 24118, 24443, 24768, 25093, 25418, 25743, 26068,
       26393, 26718, 27043, 27368, 27693, 28018, 28343, 28668, 28993,
       29318, 29643, 29968, 30293, 30618, 30943, 31268, 31593, 31918,
       32243])

In [8]:
df_amostra_sistematica = dataset.iloc[indices]
df_amostra_sistematica.head()

age      workclass  final-weight      education  education-num  \
68     49   Self-emp-inc        191681   Some-college             10   
393    34      State-gov         98101      Bachelors             13   
718    22        Private        214399   Some-college             10   
1043   44        Private        167005      Bachelors             13   
1368   52        Private        152234        HS-grad              9   

           marital-status        occupation relationship                 race  \
68     Married-civ-spouse   Exec-managerial      Husband                White   
393    Married-civ-spouse   Exec-managerial      Husband                White   
718         Never-married             Sales    Own-child                White   
1043   Married-civ-spouse   Exec-managerial      Husband                White   
1368   Married-civ-spouse   Exec-managerial      Husband   Asian-Pac-Islander   

          sex  capital-gain  capital-loos  hour-per-week  native-country  \
68       Male             0             0             50   United-States   
393      Male          7688             0             45               ?   
718    Female             0             0             15   United-States   
1043     Male          7688             0             60   United-States   
1368     Male         99999             0             40           Japan   

      income  
68      >50K  
393     >50K  
718    <=50K  
1043    >50K  
1368    >50K

### Amostragem por Grupos

In [9]:
len(dataset) / 10

3256.1

In [10]:
grupos = []
id_grupo = 0
contagem = 0

for _ in dataset.iterrows():
    grupos.append(id_grupo)
    contagem += 1
    if contagem > 3256:
        contagem = 0
        id_grupo += 1

In [ ]:
print(grupos) # Divisão por grupos

In [12]:
np.unique(grupos, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3257, 3248],
       dtype=int64))

In [13]:
# Criadno coluna 'grupo'
dataset['grupo'] = grupos

In [14]:
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  grupo  
0          2174             0             40   United-States   <=50K      0  
1             0             0             13   United-States   <=50K      0  
2             0             0             40   United-States   <=50K      0  
3             0             0             40   United-States   <=50K      0  
4             0             0             40            Cuba   <=50K      0

### Amostragem Estratificada

In [15]:
from sklearn.model_selection import StratifiedShuffleSplit

In [16]:
dataset['income'].value_counts()

 <=50K    24720
 >50K      7841
Name: income, dtype: int64

In [20]:
split = StratifiedShuffleSplit(test_size=0.1) # Divisão de base de dados repassando o tamanho da amostra
# Criação de 2 colunas, uma criada com os 10% desejados e outra com o resto dos dados
for x,y in split.split(dataset, dataset['income']):
    df_x = dataset.iloc[x] # 90% - Base
    df_y = dataset.iloc[y] # 10% - Testes

In [21]:
df_x.shape, df_y.shape

((29304, 16), (3257, 16))

### Amostragem de Reservatório

In [24]:
def amostragem_reservatorio(dataset, amostras):
    stream = []
    for i in range(len(dataset)):
        stream.append(i)
    i = 0
    tamanho = len(dataset)
    
    reservatorio = [0] * amostras
    for i in range(amostras):
        reservatorio[i] = stream[i]
    
    while i < tamanho:
        j = random.randrange(i + 1)
        if j < amostras:
            reservatorio[j] = stream[i]
        i += 1

    return dataset.iloc[reservatorio]    

In [26]:
def_amostragem = amostragem_reservatorio(dataset, 100)
def_amostragem.shape

(100, 16)

In [27]:
def_amostragem.head()

age workclass  final-weight      education  education-num  \
12635   41   Private        220694      Bachelors             13   
20771   23   Private        210526        HS-grad              9   
3058    29   Private        173652   Some-college             10   
4651    36   Private        288049        HS-grad              9   
14560   33   Private        222221        HS-grad              9   

            marital-status        occupation    relationship    race      sex  \
12635             Divorced     Other-service   Not-in-family   White     Male   
20771        Never-married      Adm-clerical       Own-child   White     Male   
3058         Never-married      Adm-clerical       Own-child   White   Female   
4651    Married-civ-spouse   Exec-managerial         Husband   White     Male   
14560   Married-civ-spouse   Exec-managerial         Husband   White     Male   

       capital-gain  capital-loos  hour-per-week  native-country  income  \
12635             0             0             37   United-States   <=50K   
20771             0             0             40   United-States   <=50K   
3058              0             0             40   United-States   <=50K   
4651              0             0             45   United-States   <=50K   
14560          7298             0             45   United-States    >50K   

       grupo  
12635      3  
20771      6  
3058       0  
4651       1  
14560      4